source 'http://rubygems.org'

# Specify your gem's dependencies in metadata.gemspec
gem 'sinatra-synchrony'
gem 'em-mongo'
gem 'thin'

group :development do
  gem 'guard'
  gem 'guard-minitest'
  gem 'rb-fsevent', :require => false
  gem 'growl_notify' # => brew install growlnotify
end

group :test do
  gem 'colorific'
  gem 'mongo'
end
