source 'http://rubygems.org'

# Specify your gem's dependencies in registry.gemspec
#gemspec
gem 'mongo'
gem 'bson_ext'
gem 'activemodel', :require => 'active_model'
gem 'sinatra', :require => 'sinatra/base'
gem 'thin'
gem 'mongodb_model'

group :development do
  gem 'guard'
  gem 'guard-rspec'
  gem 'rb-fsevent', :require => false
  gem 'growl_notify' # => brew install growlnotify
  gem 'yard'
  gem 'rdiscount'
end

group :test do
  gem 'rspec'
  gem 'rack-test', :require => 'rack/test'
end
