source 'http://rubygems.org'

# Specify your gem's dependencies in meta.gemspec
#gemspec
gem 'mongo'
gem 'bson_ext'
gem 'mysql2'
gem 'sinatra'
gem 'thin'

group :development do
  gem 'guard'
  gem 'guard-rspec'
  gem 'ruby_gntp'
  gem 'yard'
  gem 'rdiscount'
  gem 'sinatra-reloader'
end

group :test do
  gem 'rspec'
  gem 'rack-test', :require => 'rack/test'
  gem 'simplecov'
end
