source 'http://rubygems.org'

# Specify your gem's dependencies in registry.gemspec
#gemspec

group :development do
  gem 'guard'
  gem 'guard-rspec'
  gem 'rb-fsevent', :require => false
  gem 'growl_notify' # => brew install growlnotify
  gem 'yard'
  gem 'rdiscount'
end

group :test do
  gem 'rspec'
end
