source 'http://rubygems.org'

# Specify your gem's dependencies in meta.gemspec
#gemspec

group :development do
  gem 'guard'
  gem 'guard-rspec'
  gem 'ruby_gntp'
  gem 'yard'
  gem 'rdiscount'
end

group :test do
  gem 'rspec'
  gem 'simplecov'
end
