source 'http://rubygems.org'

# Specify your gem's dependencies in meta.gemspec
#gemspec

group :development do
  gem 'guard'
  gem 'guard-rspec'
  gem 'rb-fsevent'
  gem 'rb-readline'
  gem 'growl_notify' # => brew install growlnotify
  gem 'yard'
  gem 'rdiscount'
end

group :test do
  gem 'rspec'
  gem 'simplecov'
end
