#!/usr/bin/env rake
require "bundler/gem_tasks"
require 'rake/testtask'
require 'fileutils'

Rake::TestTask.new(:all) do |t|
  t.libs.push "lib"
  t.test_files = FileList['spec/*/*_spec.rb']
end

desc "Count lines of source .rb files"
task :lines do
  system "find . -name '*.rb' | xargs wc -l"
end

desc "Generate YARD documentation"
task :ydoc do
  require File.join(File.dirname(__FILE__), 'lib', 'common')
  output = "~/workspace/gh-pages/visor/common"
  system "rm -rf #{output}*"
  system "yardoc lib/**/*.rb lib/registry/**/*.rb -o #{output} --no-save --title VISoR --main ../README.md"
  system "cd #{output} && git add . && git commit -am 'documentation updated' && git push origin gh-pages"
end

task :default => :list

task :list do
  system 'rake -T'
end
