#!/usr/bin/env rake
require "bundler/gem_tasks"
require 'rake/testtask'
require 'fileutils'

Rake::TestTask.new(:all) do |t|
  t.libs.push "lib"
  t.test_files = FileList['spec/*/*_spec.rb']
end

desc "Start Guard"
task :g do
  system "bundle exec guard start"
end

desc "Count lines of source .rb files"
task :lines do
  system "find . -name '*.rb' | xargs wc -l"
end

task :default => :list

task :list do
  system 'rake -T'
end
