source 'http://rubygems.org'

# Specify your gem's dependencies in meta.gemspec
#gemspec
gem 'goliath', :git => 'https://github.com/postrank-labs/goliath.git'
gem 'em-http-request', :git => 'https://github.com/igrigorik/em-http-request.git'

group :development do
  gem 'guard'
  gem 'guard-rspec'
  gem 'rb-fsevent'
  gem 'growl_notify' # => brew install growlnotify
  gem 'yard'
  gem 'rdiscount'
end

group :test do
  gem 'rspec'
  gem 'simplecov'
end
