source 'http://rubygems.org'

# Specify your gem's dependencies in meta.gemspec
#gemspec

gem 'sinatra'
gem 'google_visualr'

group :development do
  gem 'sinatra-reloader'
end

group :test do
  gem 'rspec'
  gem 'simplecov'
end
