# A sample Guardfile
# More info at https://github.com/guard/guard#readme

guard 'rspec', :cli => "--color --format nested --fail-fast" do
  watch(%r|^spec/(.*)_spec\.rb|)
  watch(%r|^spec/extensions/(.*)_spec\.rb|)
  watch(%r|^lib/(.*)\.rb|)                    { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r|^lib/common/(.*)\.rb|)           { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r|^spec/spec_helper\.rb|)    { "spec" }
end
